In [24]:
import pandas as pd
data = pd.read_csv('regression_practice.csv')

data.head()

,customer_id,age,tenure_months,monthly_spend,sessions_per_week,region,premium,annual_value
0,100000,22,74,150.02,3.90,east,0,5745
1,100001,55,94,89.30,0.80,south,1,6130
2,100002,49,89,29.17,3.85,east,1,6272
3,100003,39,16,31.31,3.85,north,0,4606
4,100004,38,99,219.94,4.20,south,0,6572

In [25]:
#region kısmı kategorik olduğu için one hot encoding uygulayacağız.

encoded_data = pd.get_dummies(data,columns=['region'])
encoded_data

encoded_data=encoded_data.drop(columns=['region_west'])
encoded_data

,customer_id,age,tenure_months,monthly_spend,sessions_per_week,premium,annual_value,region_east,region_north,region_south
0,100000,22,74,150.02,3.90,0,5745,True,False,False
1,100001,55,94,89.30,0.80,1,6130,False,False,True
2,100002,49,89,29.17,3.85,1,6272,True,False,False
3,100003,39,16,31.31,3.85,0,4606,False,True,False
4,100004,38,99,219.94,4.20,0,6572,False,False,True
...,...,...,...,...,...,...,...,...,...,...
595,100595,56,76,33.69,6.75,1,6728,False,True,False
596,100596,45,86,147.19,4.41,0,6251,True,False,False
597,100597,55,118,19.95,0.58,0,5304,False,False,True
598,100598,48,97,131.92,5.91,0,7472,False,False,False
599,100599,48,75,69.96,1.18,1,6080,False,False,False

In [26]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
from sklearn.model_selection import train_test_split

y= encoded_data.iloc[:,6:7]
y

x=encoded_data.drop(columns=['annual_value','customer_id'])
x

,age,tenure_months,monthly_spend,sessions_per_week,premium,region_east,region_north,region_south
0,22,74,150.02,3.90,0,True,False,False
1,55,94,89.30,0.80,1,False,False,True
2,49,89,29.17,3.85,1,True,False,False
3,39,16,31.31,3.85,0,False,True,False
4,38,99,219.94,4.20,0,False,False,True
...,...,...,...,...,...,...,...,...
595,56,76,33.69,6.75,1,False,True,False
596,45,86,147.19,4.41,0,True,False,False
597,55,118,19.95,0.58,0,False,False,True
598,48,97,131.92,5.91,0,False,False,False
599,48,75,69.96,1.18,1,False,False,False

In [27]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.33,random_state=0)
lr.fit(x_train,y_train)
lr_predict=lr.predict(x_test)
lr_predict

array([[5564.40487037],
       [5675.09752791],
       [6378.01382737],
       [6693.80601393],
       [7243.14852046],
       [5958.56455278],
       [6385.35439892],
       [6465.72030017],
       [6148.75989268],
       [6339.49568058],
       [5648.30553637],
       [6329.77332629],
       [6391.98083236],
       [5228.18415167],
       [7049.71514941],
       [5801.92968407],
       [5733.21114869],
       [7128.8090659 ],
       [6271.28343926],
       [7069.18627908],
       [6084.56025135],
       [7063.51714087],
       [7470.77757981],
       [5483.53204466],
       [4988.46746898],
       [5143.98328158],
       [6409.08195215],
       [5850.06304592],
       [5453.07929489],
       [6288.50380445],
       [6905.27311128],
       [6589.40035344],
       [5963.619675  ],
       [6432.00947205],
       [5130.39722437],
       [7250.78297648],
       [7366.83867684],
       [7351.48959057],
       [5114.83426011],
       [6014.49497685],
       [6263.95697129],
       [5241.50710113],
       [6462.46417431],
       [4689.53540022],
       [6868.77763225],
       [4811.34594777],
       [6140.54362738],
       [6655.46248527],
       [5834.98167132],
       [6573.76757067],
       [4539.89693104],
       [5172.36831493],
       [5991.67213891],
       [4942.46048298],
       [4099.23412445],
       [6969.99560003],
       [5811.27219079],
       [5545.39376848],
       [7722.64035369],
       [5755.87965128],
       [6865.86254085],
       [5209.56672672],
       [4898.40589129],
       [7056.52491141],
       [5976.67970838],
       [6024.257826  ],
       [6197.45341198],
       [6965.18914505],
       [6534.10841684],
       [5415.04213531],
       [5042.99062269],
       [5874.15803132],
       [5706.70862854],
       [6590.73532453],
       [5981.24434002],
       [4972.71639879],
       [5054.18608333],
       [5054.71047371],
       [5424.80144882],
       [6054.78608331],
       [5270.85727435],
       [5518.17101958],
       [5369.54626498],
       [6088.7789201 ],
       [5720.15543838],
       [5648.58997761],
       [5660.84462444],
       [5623.09033078],
       [5730.17197878],
       [6268.40112912],
       [6250.03602876],
       [5928.58425054],
       [6842.49109581],
       [6467.87684956],
       [5174.76047686],
       [6205.00068362],
       [6659.79126469],
       [5978.97416286],
       [5631.89123823],
       [5885.62211568],
       [5299.65407807],
       [5852.05055833],
       [6283.32749607],
       [5338.38492506],
       [5776.47166418],
       [6303.21075651],
       [5994.69926501],
       [4876.90201281],
       [4780.14390954],
       [5618.43102556],
       [6953.77665769],
       [6761.63198058],
       [6041.18709557],
       [5796.4789601 ],
       [6990.05054549],
       [6487.98210732],
       [6229.36899124],
       [5377.84524179],
       [6883.88464656],
       [6284.95266702],
       [5846.17893185],
       [7283.58315653],
       [5397.68332724],
       [7092.22893056],
       [5012.77919813],
       [5460.27032822],
       [5494.253344  ],
       [5878.65532097],
       [5506.75008025],
       [6323.00762752],
       [4951.31505849],
       [4898.82211315],
       [5819.05479303],
       [6613.51626263],
       [6682.16143403],
       [5574.70716621],
       [4892.64704827],
       [7250.98422501],
       [6055.32532494],
       [6430.89220999],
       [5341.67836298],
       [5655.6051956 ],
       [6964.06842168],
       [4990.90421643],
       [5148.11581985],
       [6722.42075857],
       [5877.34771186],
       [5797.6248357 ],
       [5805.35328796],
       [5775.82434689],
       [5920.98326429],
       [5825.35369979],
       [5398.45015224],
       [5457.57790878],
       [5783.86712351],
       [6236.76758824],
       [6362.86333893],
       [6228.33153408],
       [6120.06732939],
       [6264.62379531],
       [6276.85393524],
       [5394.86522964],
       [5798.10493048],
       [5644.29772415],
       [5126.90765803],
       [7073.47900348],
       [5989.75767521],
       [5013.73892672],
       [6226.80892629],
       [6369.00887153],
       [4891.02556258],
       [7033.54411959],
       [6254.96204685],
       [5352.1433601 ],
       [6768.19176938],
       [6625.13978795],
       [5608.55598531],
       [6472.51404516],
       [5480.33926836],
       [6206.33469894],
       [5153.12621001],
       [7678.13633365],
       [6445.80635246],
       [7171.09153308],
       [5952.19422981],
       [5887.15582913],
       [7056.12138321],
       [6830.91072191],
       [7073.70149119],
       [6837.39711433],
       [6420.0069036 ],
       [6136.22487871],
       [5839.96611275],
       [6884.95903999],
       [3937.24693233],
       [6327.77113646],
       [5618.16960205],
       [6232.11412074]])

In [28]:
from sklearn.metrics import r2_score
r2_linear = r2_score(y_test,lr_predict)
r2_linear

0.6708673323486485

In [29]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(max_depth=5,random_state=42)
dt.fit(x_train,y_train)
dt_predict = dt.predict(x_test)
r2_dt = r2_score(y_test,dt_predict)
r2_dt

0.4630397661201273

In [30]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)
rf_predict = rf.predict(x_test)
r2_rf = r2_score(y_test,rf_predict)
r2_rf

C:\Users\Görkem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.6437730302909388

In [31]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
#SVR noktalar arası mesafe hesapladığı için elimizdeki değerleri scale ediyoruz.

sc_x=StandardScaler()
sc_y=StandardScaler()
x_train_scaled=sc_x.fit_transform(x_train)
x_test_scaled=sc_x.transform(x_test)
y_train_scaled = sc_y.fit_transform(y_train.values.reshape(-1,1)).ravel()

svr =SVR(kernel='rbf')
svr.fit(x_train_scaled,y_train_scaled)
svr_predict=sc_y.inverse_transform(svr.predict(x_test_scaled).reshape(-1,1))

r2_svr = r2_score(y_test,svr_predict)
r2_svr

0.654504485093145

In [32]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
x_poly_train = poly.fit_transform(x_train)
x_poly_test = poly.transform(x_test)
lr_poly=LinearRegression()
lr_poly.fit(x_poly_train,y_train)

r2_poly=r2_score(y_test,lr_poly.predict(x_poly_test))
r2_poly

0.6976922472882439

# SONUÇ
* Linear Regression -> 0.67
* Decision Tree -> 0.46
* Random Forest -> 0.64
* SVR -> 0.65
* 🏆 Polynomial Regression -> 0.69